### ISSUE TITLE
### Summary

### ISSUE THREAD

**Issue by jbird1repo** [skills/introduction-to-github#1019]
### Summary

A clear and concise description of what the bug is, and what you expected to happen.

### How to reproduce

2. Click on '...'
3. Scroll down to '...'

Please include screenshots.

### Additional context

_Originally posted by @jbird1repo in https://github.com/skills/introduction-to-github/issues/1006_

**Comment by Intralacerk** [comment]
Formalización completa

**Comment by Intralacerk** [comment]
Alistar programa

**Comment by Intralacerk** [comment]
Activacion generalizada
