### ISSUE TITLE
【FAQS-PUBLIC】Does Qatar give full refunds

### ISSUE THREAD

**Issue by Trentbo** [skills/introduction-to-github#1114]
[maintainer edit for spammy content]

**Comment by Trentbo** [comment]
https://github.com/skills/introduction-to-github/issues/1114https://github.com/skills/introduction-to-github/issues/1114https://github.com/skills/introduction-to-github/issues/1114https://github.com/skills/introduction-to-github/issues/1114

**Comment by RONErony2** [comment]
Ronerony read me
