### ISSUE TITLE
[Quick!!Guide!!Respond™]Faqs-Public-Does Qatar give full refunds 

### ISSUE THREAD

**Issue by Trentbo** [skills/introduction-to-github#1117]
[maintainer edit for spammy content]

**Comment by Jasbir88** [comment]
Qatar Airways Refund and Cancellation Policy (General Guidelines)

-24-Hour Risk-Free Cancellation:
Qatar Airways allows passengers to cancel their tickets within 24 hours of booking for a full refund, provided the booking was made at least 7 days before departure.

-Refundable vs Non-Refundable Tickets:
Refundable Tickets: Eligible for a full refund if cancelled as per the fare rules.
Non-Refundable Tickets: Cannot be refunded but may offer a travel credit for future bookings.

Cancellation Beyond 24 Hours:
Refund eligibility depends on the fare type purchased. Additional fees may apply for cancellations made after the risk-free window.

Checking Refund Eligibility:
Review your booking confirmation email or the fare conditions on your ticket.
Contacting Qatar Airways Directly:

Visit the official Qatar Airways website at [www.qatarairways.com](https://www.qatarairways.com/) or call their official customer service number listed on their website.
