### ISSUE TITLE
Typo: Inconsistent message: "Add PROFILE.md" vs "Adding PROFILE.md"

### ISSUE THREAD

**Issue by luykxpi** [skills/introduction-to-github#121]
**Describe the bug**
The tutorial text says: "First, enter Add PROFILE.md in the first text-entry field below Commit new file. Then, if you want to confirm what your screen should look like, expand the dropdown below."
But the screenshot shows the message as "Adding PROFILE.md".

**Comment by Kingmax1981** [comment]
> **Describe the bug**
> 
> The tutorial text says: "First, enter Add PROFILE.md in the first text-entry field below Commit new file. Then, if you want to confirm what your screen should look like, expand the dropdown below."
> 
> But the screenshot shows the message as "Adding PROFILE.md".
> 
> 
> 
> 

[![image](https://user-images.githubusercontent.com/111104349/197366651-b182cb63-facd-40c6-841e-a3924e465573.png)]()

**Comment by vladoss888** [comment]
https://github.com/skills/introduction-to-github/issues/121#issue-1402854861

**Comment by cmwilson21** [comment]
Closing this as it appears it was fixed in the content overhaul
