### ISSUE TITLE
Issue #16950

### ISSUE THREAD

**Issue by aipwe15** [skills/introduction-to-github#14]
Issue #16950

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

__最初由 @vedant205 在 https://github.com/github/docs/pull/18525 发布__

**Comment by rafaamuhsen** [comment]
> Issue #16950
> 
> 
> 
> 
> 
> 
> 
> ### Why:
> 
> 
> 
> Closes [issue link]
> 
> 
> 
> 
> 
> 
> 
> ### What's being changed:
> 
> 
> 
> 
> 
> 
> 
> ### Check off the following:
> 
> 
> 
> - [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
> 
> - [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 
> 
> 
> ### Writer impact (This section is for GitHub staff members only):
> 
> 
> 
> - [ ] This pull request impacts the contribution experience
> 
>   - [ ] I have added the 'writer impact' label
> 
>   - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")
> 
> 
> 
> 
> 
> 
> 
> __最初由 @vedant205 在 https://github.com/github/docs/pull/18525 发布__

**Comment by rafaamuhsen** [comment]
> > Issue #16950
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > ### Why:
> > 
> > 
> > 
> > Closes [issue link]
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > ### What's being changed:
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > ### Check off the following:
> > 
> > 
> > 
> > - [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
> > 
> > - [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> > 
> > 
> > 
> > ### Writer impact (This section is for GitHub staff members only):
> > 
> > 
> > 
> > - [ ] This pull request impacts the contribution experience
> > 
> >   - [ ] I have added the 'writer impact' label
> > 
> >   - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > __最初由 @vedant205 在 https://github.com/github/docs/pull/18525 发布__
> 
>

**Comment by Alfiekmote20** [comment]
unsubscribe

Pada tanggal Jum, 10 Jun 2022 17.00, rafaamuhsen ***@***.***>
menulis:
