### ISSUE TITLE
[Featured] 

### ISSUE THREAD

**Issue by j1mmb0slice** [skills/introduction-to-github#160]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [The text color is the same as the background image color. Ya can't see shit.]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by j1mmb0slice** [comment]
I should have used the other color instaed

**Comment by Alfiekmote20** [comment]
Unsubscribe

Pada tanggal Sel, 8 Nov 2022 08.53, j1mmb0slice ***@***.***>
menulis:

**Comment by Alfiekmote20** [comment]
Unsubscribe

Pada tanggal Sel, 8 Nov 2022 08.54, j1mmb0slice ***@***.***>
menulis:
