### ISSUE TITLE
[Bug] Update the "Use this template" step to reflect recent GitHub UI changes

### ISSUE THREAD

**Issue by StarfieldExplorer** [skills/introduction-to-github#163]
**Describe the bug**
The GitHub Web UI recently changed as a result of the Codespaces feature. This means the opening instructions, under "How to start this course," are no longer consistent with the UI. An update to this would be helpful.

**To Reproduce**
1. Go to: https://github.com/skills/introduction-to-github
2. Compare the instructions and image under "How to start this course" with the Web UI.

**Expected behavior**
Right-click on and open a new tab using the "Use this template" button. Now one must left-click it and then right-click on the "Create a new template" option from the drop-down menu.

**Device information**
 - OS: macOS
 - Browser: Firefox
 - Version: 106.0.5

**Comment by Alfiekmote20** [comment]
Unsubscribe

Pada tanggal Sab, 12 Nov 2022 03.40, StarfieldExplorer <
***@***.***> menulis:

**Comment by sinsukehlab** [comment]
I will first add a commit to my PR skills/template-template#21.

**Comment by 4gittest** [comment]
"Use this template" is not shown at all, when you are not logged in. I just visited github.com for learning the first steps. I found this repo by using the menu in left upper corner...explore...github Skills. So at this point, Prerequisites = none is not true. I'm sure a lot of other folks just give up at that point. As there is no explanation for the missing button. I think "creating an account" should not be an extra step in this repo, but it should be addressed in the introduction.

**Comment by AzManApple42** [comment]
> "Use this template" is not shown at all, when you are not logged in. I just visited github.com for learning the first steps. I found this repo by using the menu in left upper corner...product...explore...github skills. So at this point, Prerequisites = none is not true. I'm sure a lot of other folks just give up at that point. As there is no explanation for the missing button. I think "creating an account" should not be an extra step in this repo, but it should be addressed in the introduction.

I second this, if you are brand new to the site and want to get started with learning you first need to create an account.

**Comment by mfghelth** [comment]
Good

**Comment by congruentx** [comment]
> "Use this template" is not shown at all, when you are not logged in. I just visited github.com for learning the first steps. I found this repo by using the menu in left upper corner...product...explore...github skills. So at this point, Prerequisites = none is not true. I'm sure a lot of other folks just give up at that point. As there is no explanation for the missing button. I think "creating an account" should not be an extra step in this repo, but it should be addressed in the introduction.

Agreed.  The documentation is not intuitive at all.  At this point, just rather watch some useful video tutorials on YT.

**Comment by CodefortheCarolinas** [comment]
It will be helpful if these instructions specifically state that this step should open a new tab and references the type(s) of click to use to open a new tab (like right click or command-click).

**Comment by bionicworx** [comment]
Right-clicking on `Use this template` does nothing for me. I'll have to left-click and select either `create a new repository` or `Open in a codespace`. 

The instructions should be updated with either selections.

**Comment by sinsukehlab** [comment]
> I will first add a commit to my PR [skills/template-template#20](https://github.com/skills/template-template/pull/20).

I will open another PR in this repository to fix this issue.

**Comment by heiskr** [comment]
We've updated the courses to include the button you'll need directly in the README, and it will prompt you to log in if you are not.
