### ISSUE TITLE
[Bug]Cannot create 'my-first-branch'  

### ISSUE THREAD

**Issue by damo-maker** [skills/introduction-to-github#222]
**Describe the bug**
There is no Create branch button in the main drop down box

**To Reproduce**
1. Go to Code tab
2. Click on 'main'
3. enter 'my-first-branch' in the main drop down
4. With 'branches' selected can only see 'Nothing to show'

**Expected behavior**
I expected  to see and be able click on 'Create branch:my-first-branch from main'

**Screenshots**

![Screenshot 2023-01-13 at 15 31 29](https://user-images.githubusercontent.com/57318637/212239014-b83cb815-f739-4cf5-9fb1-9c69a37a99dc.jpg)

**Device information**
I am on a Mac M1 running Ventura OS

**Comment by ranadip01in** [comment]
I think the bug is solved. That bug is not occured in my windows machine. You should try again.

**Comment by borisUOP** [comment]
Hi, I think the bug still persists.

**Comment by skroger30** [comment]
I think the bug still persists. I cannot see the option to create my-first-branch.

**Comment by andrewgreen76** [comment]
**_My solution_**: I just used ChatGPT to help me nail this sucker via the Bash terminal. Check out [this link](https://github.com/andrewgreen76/flygreen/tree/main/e_hkbk/b_gift-magic/7_linux_trml/e_git-why_trblsht) on my repo. You'll have to excuse the ever-changing mess I make on my repo, but hopefully the top files with somewhat descriptive names will work well enough for you to create a new branch. 

Never stop trying. 

(BTW, I'm using Ubuntu, in case if you are curious, but I don't think it really matters. I think it's an issue on the server side. Nothing about any client should change the remote repo's features/content.)

**Comment by sinsukehlab** [comment]
It seems that you were trying to create a new branch on the skills/introduction-to-github repository, to which you don't have write access. You should first generate your new repository and create a new branch on that repository.

**Comment by Mokatoto** [comment]
نعم

**Comment by cmwilson21** [comment]
I'm going to go ahead and close this issue as it seems to have been solved 👍
