### ISSUE TITLE
The word Step is used for 2 different levels

### ISSUE THREAD

**Issue by CodefortheCarolinas** [skills/introduction-to-github#236]
**Description**
The word Step is used to describe the main parts of the tutorial and the actions taken within each part.

**To Reproduce**
1. Go to [Introduction to GitHub](https://github.com/skills/introduction-to-github)'
2. Click on 'Step 1 Create a Branch'

This ambiguous use of the word step is throughout this tutorial and others.

**Expected behavior**
A phrase like "Step 2" or "next step" should have a unique meaning within the tutorial.

**Additional context**
It would be helpful to refer to the four large parts of the tutorial as Part 1, Part 2, Part 3, and Part 4. Then the word step could be used for the specific steps within each part. This ambiguous use of the word step is especially confusing when walking a group of new users through the tutorial. If the instructor says "next step," different participants will interpret that in a different way. While it would take a little time to do this throughout all tutorials, it would improve their usability.

**Comment by cmwilson21** [comment]
@CodefortheCarolinas Thanks for surfacing this! I'll bring this feedback to the team 💛

**Comment by heiskr** [comment]
Internally, we've referred to the top level as steps and the `ol > li` level as tasks. Given the course content comes from various sources, might need a review to ensure we're using that language consistently.

**Comment by zhu811** [comment]
It's good

**Comment by hngnhv** [comment]
cảm ơn

**Comment by mnmnmnto** [comment]
> **Description** The word Step is used to describe the main parts of the tutorial and the actions taken within each part.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to [Introduction to GitHub](https://github.com/skills/introduction-to-github)'
> 2. Click on 'Step 1 Create a Branch'
> 
> This ambiguous use of the word step is throughout this tutorial and others.
> 
> **Expected behavior** A phrase like "Step 2" or "next step" should have a unique meaning within the tutorial.
> 
> **Additional context** It would be helpful to refer to the four large parts of the tutorial as Part 1, Part 2, Part 3, and Part 4. Then the word step could be used for the specific steps within each part. This ambiguous use of the word step is especially confusing when walking a group of new users through the tutorial. If the instructor says "next step," different participants will interpret that in a different way. While it would take a little time to do this throughout all tutorials, it would improve their usability.

**Comment by ManojJagatap333** [comment]
Tool X

**Comment by wm26kwan** [comment]
A new exercise

**Comment by hectorsector** [comment]
Thanks for the feedback, we've got an internal issue (https://github.com/github/skills/issues/161) open to look into this topic so I'll mark this as closed.

**Comment by thuyanets** [comment]
Hello
