### ISSUE TITLE
Video "Creating Pull Request" Assumes an Issue

### ISSUE THREAD

**Issue by CodefortheCarolinas** [skills/introduction-to-github#237]
**Describe the bug**
The Creating Pull Request video assumes that a pull request is created to resolve an issue. However, the tutorial is framed around the user creating a pull request to make a change that is not associated with an issue.

**To Reproduce**
1. Go to ['Introduction to GitHub'](https://github.com/skills/introduction-to-github)
2. Click on 'Step 3 Open a pull request'
3. Click on [Video: Introduction to pull requests](https://youtu.be/kJr-PIfLDl4)
4. See error, reference to "Issue"

**Expected behavior**
Video explains pull request without making reference to an issue. OR (more complicated) tutorial is adjusted to have users work on an issue, like "Profile is missing README."

**Comment by heiskr** [comment]
Thank you for opening this issue. We're removed these videos from the courses and YouTube.
