### ISSUE TITLE
RunFailed Errors sent by email

### ISSUE THREAD

**Issue by CodefortheCarolinas** [skills/introduction-to-github#238]
**Describe the bug**
At 3 steps in the tutorial, user is sent an email notification of a RunFailed error.

**To Reproduce**
1. Go to '[Introduction to GitHub](https://github.com/skills/introduction-to-github)'
2. Click on 'Step 1 Create a branch, Step 2 Commit a file OR Step 3 Create a pull request.'
3. Click on 'Create branch: my-first-branch, Commit new file, OR Create pull request '
4. Check for error message in email.

**Expected behavior**
Ideally, no error message is generated. If that's not possible, prevent the error message from being sent to the user. If that's not possible either, include a note at the top of the tutorial like "During this tutorial, you may get emails with a subject line RunFailed Error. That is expected and you can delete the emails."

**Screenshots**
![image](https://user-images.githubusercontent.com/99441930/213515520-67679ba4-0752-4bf9-8fc1-87b04b581938.png)

**Device information**
 - Type: [PC]
 - OS: [Windows11]
 - Browser [Chrome]
 - Version [ 109.0.5414.75 (Official Build) (64-bit)]

**Additional context**
This happened both times I completed the tutorial and it happened to multiple other users with different system setups.

Not only did this make me wonder if I was doing something wrong, it also meant I had to reassure each other participant that nothing was wrong for them, either. So even though the error messages don't seem to interfere with the workings of the tutorial, they waste time and reduce users' confidence in themselves, the tutorial, and the software.

**Comment by Emily-Laidlaw** [comment]
Hello, I am just a student.  I received runtime errors and found the automation does not work as mentioned in the tutorial.  I did the course many times, trying to identify where I made a mistake.  Apparently, the tutorial instructions are supposed to truncate after 20 seconds - and this never worked for me.   I don't know who to speak to, to find out if it is me or the system.  I am having issues with other tutorials as well "Communicate with Markdown" where there is no "pull request" to access  as outlined in the tutorial.

**Comment by abigailconstantino** [comment]
> Olá, sou apenas um estudante. Recebi erros de tempo de execução e descobri que a automação não funciona conforme mencionado no tutorial. Fiz o percurso várias vezes, tentando identificar onde errei. Aparentemente, as instruções do tutorial devem ser truncadas após 20 segundos - e isso nunca funcionou para mim. Não sei com quem falar, para saber se sou eu ou o sistema. Estou tendo problemas com outros tutoriais também "Comunicar-se com Markdown", onde não há "solicitação pull" para acessar, conforme descrito no tutorial.

**Comment by cmwilson21** [comment]
@CodefortheCarolinas Thanks again for surfacing this. Running it by the team 👍

**Comment by heiskr** [comment]
Thank you for opening this issue. A recent API change https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/ adversely impacted Skills courses, and we have remediated all courses for that issue. You're welcome to try the course again and let us know if you experience further issues.
