### ISSUE TITLE
Role of videos not clear to users

### ISSUE THREAD

**Issue by CodefortheCarolinas** [skills/introduction-to-github#239]
**Describe the bug**
The structure of the tutorials, including the role of the brief videos, is not clear to users. This structure could be explained on the main GitHub Skills page.

**To Reproduce**
1. Go to '[GitHub Skills](https://skills.github.com/)'

**Expected behavior**
A sentence below Our Courses explains the structure of the courses. A good sentence might be "In these courses you will read about GitHub, watching brief videos, and complete interactive hands-on practice activities."

You might also consider embedding the videos rather than linking to them, to increase their visibility.

**Additional context**
The structure of these tutorials is what makes them excellent. I have encountered multiple people who don't realize the tutorials include videos. This includes someone who completed the tutorial without noticing the videos, and therefore didn't get the full benefit. It also include people suggesting making an hour-long recording of someone demonstrating the tutorial, which is of course not ideal.  I think these tutorials would be more appealing and useful if the presence of brief, on-point videos was more obvious to new users.

**Comment by cmwilson21** [comment]
@CodefortheCarolinas Thanks for this great feedback! I'll bring it to the team 💖

**Comment by heiskr** [comment]
Thank you for opening this issue. We're removed the old videos from YouTube and our courses.
