### ISSUE TITLE
field to create branches does not read the new branch name

### ISSUE THREAD

**Issue by maxinieva** [skills/introduction-to-github#249]
field to create branches does not read the new branch name

![image](https://user-images.githubusercontent.com/122228815/214176895-c4da56c1-7603-428b-9ebd-e96c1780f54d.png)

when i wrote the name of the new branch it does not appear the option "Create branch: my-first-branch from main"

**Comment by arpdkvcs** [comment]
Same here

**Comment by andronic52** [comment]
its below "branches" and "tags" and above view all branches, u just click that and ur done

**Comment by arpdkvcs** [comment]
@andronic52 I think that is clear, but the problem was that that button or section you just described was missing. Since then I have managed somehow (have no idea how).

**Comment by Janek1985h** [comment]
> field to create branches does not read the new branch name
> 
> ![image](https://user-images.githubusercontent.com/122228815/214176895-c4da56c1-7603-428b-9ebd-e96c1780f54d.png)
> 
> when i wrote the name of the new branch it does not appear the option "Create branch: my-first-branch from main"

**Comment by Champagne0497** [comment]
can someone explain me how to creat a new branch? i will appreciate it

**Comment by Amory73** [comment]
لافيو+967776575795

**Comment by megatrona69** [comment]
me falta practica

**Comment by aldairQQ** [comment]
Use the command git checkout -b NEW-NAME-BRANCH, this will create and allow you to move to the new branch at the same time

**Comment by Icezazazaz** [comment]
Thank you

**Comment by TheeTw23** [comment]
Tags click

**Comment by favour-22** [comment]
`okay`

**Comment by long99vip** [comment]
https://github.com/skills/introduction-to-github/issues/249#issue-1554003987
