### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Cellfin** [skills/introduction-to-github#283]
**Describe the bug**

**To Reproduce**
1. Go to '...'Cellfin.
2. Click on '....'digital banking.
3. Scroll down to '....'cloud
4. See error 0000

**Expected behavior**

**Screenshots**

**Device information**
 - Type: [e.g. Android]
 - OS: [e.g. OS]

**Additional context**

**Comment by rachmari** [comment]
I'm closing this out because there is nothing added to the bug report issue template.
