### ISSUE TITLE
can't find the "use this template" button

### ISSUE THREAD

**Issue by Zuwairanajma** [skills/introduction-to-github#299]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device information**
 - Type: [e.g. iPhone6]

**Additional context**

**Comment by davidovich** [comment]
@Zuwairanajma You will need to be signed in to Github to see that button. I had the same questioning as you when I tried to navigate to the repo without being logged-in. 

Perhaps there could be a step 0: Make sure you are signed-in to your account before following the next steps.

**Comment by shaistajam** [comment]
Cant find the use this tamplate

**Comment by heiskr** [comment]
We've updated the courses to include the button you'll need directly in the template, and it will prompt you to log in if you are not.

**Comment by Hilexcruz** [comment]
I can't see it even when i'm logged in. What do i do now?
