### ISSUE TITLE
@Zuwairanajma You will need to be signed in to Github to see that button. I had the same questioning as you when I tried to navigate to the repo without being logged-in.

### ISSUE THREAD

**Issue by ebony13** [skills/introduction-to-github#307]
@Zuwairanajma You will need to be signed in to Github to see that button. I had the same questioning as you when I tried to navigate to the repo without being logged-in. 

Perhaps there could be a step 0: Make sure you are signed-in to your account before following the next steps.

_Originally posted by @davidovich in https://github.com/skills/introduction-to-github/issues/299#issuecomment-1427077871_

**Comment by cmwilson21** [comment]
@ebony13 Thanks for opening an issue. I've got this feedback noted internally so will be closing this issue 💛
