### ISSUE TITLE
Step 1, Create a branch: All jobs have failed

### ISSUE THREAD

**Issue by h4rz** [skills/introduction-to-github#314]
### Discussed in https://github.com/orgs/skills/discussions/161

<div type='discussions-op-text'>

<sup>Originally posted by **h4rz** February  4, 2023</sup>
I'm doing the `Introduction to GitHub` from the GitHub skills (https://github.com/skills/introduction-to-github) and receiving the below error message. Can someone please help me?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/20818641/216801730-7a95c487-4362-47bf-8c88-8913831e38a3.png">
</div>

**Comment by heiskr** [comment]
Hi @h4rz thanks for opening this issue. We've made some updates recently to the courses, so feel free to try again and let us know if there are still issues. Closing for now.
