### ISSUE TITLE
[Bug]can't create a branch

### ISSUE THREAD

**Issue by 00zelma** [skills/introduction-to-github#400]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device information**
 - Type: [e.g. iPhone6]

**Additional context**

**Comment by rachmari** [comment]
I don't see a bug defined here, so I'm going to close this out.

**Comment by Dieu2023** [comment]
Vào 13:59, Th 6, 19 thg 5, 2023 SELMA V S ***@***.***> đã
viết:

**Comment by Dieu2023** [comment]
Vào 0:27, Th 7, 20 thg 5, 2023 Rachael Sewell ***@***.***> đã
viết:
