### ISSUE TITLE
[Bug] master branch instead of main branch

### ISSUE THREAD

**Issue by rklie** [skills/introduction-to-github#56]
**Describe the bug**
On the [Branches](https://www.youtube.com/watch?v=xgQmu81G1yY) video linked in Step 1 the language still uses "master" instead of "main".

**To Reproduce**
1. Go to Step 1
2. Click on [Video: Branches](https://www.youtube.com/watch?v=xgQmu81G1yY)
3. Listen to the recording

**Expected behavior**
It should say main instead of master.

**Comment by kailer22** [comment]
Sheesh
