### ISSUE TITLE
[Bug] Typo on image under Step 2.4

### ISSUE THREAD

**Issue by alexis-opolka** [skills/introduction-to-github#566]
### Summary

There is a typo on the name of the repository in the image under step 2.4: [skills/introdution-to-github/blob/.../2-commit-a-file.md](https://github.com/skills/introduction-to-github/blob/861fdad7b41ee97d45bb7ef45215ad1b0e8337cb/.github/steps/2-commit-a-file.md), it should be `my-new-repository` but is currently `my-new-repoistory`.

### How to reproduce

Click on the link given above or access the file `2-commit-a-file.md` and see the following content:

![image](https://github.com/skills/introduction-to-github/assets/53085471/c81c542d-9075-4078-b6ab-d380512d27e2)

**Comment by Osagiebit** [comment]
Welcome to my GitHub profile

**Comment by yassinsharaf165** [comment]
Yassinsharaf16

**Comment by yassinsharaf165** [comment]
_**

**Comment by whiteSHADOW1234** [comment]
I have submitted a pull request (#661) to address this issue and am willing to be assigned to it. Please feel free to review the changes and let me know if any further modifications are needed.

**Comment by P1106480043** [comment]
https://github.com/skills/introduction-to-github.git
