### ISSUE TITLE
Certified SSL don´t work in FreeBSD

### ISSUE THREAD

**Issue by CarloseKan** [skills/introduction-to-github#588]
# I write this text:

sudo certbot certonly --standalone -d tudominio.com

After, I see a message too large, it finished so......

 "/tmp/certbot-log-2dcq1bkq/log or re-run Certbot with -v for more details."

I wait for your help

**Comment by rsese** [comment]
👋 !  It sounds like you're looking for help with certbot?  If so, https://github.com/certbot/certbot would be a good place to start for help.

**Comment by Faphouse** [comment]
Success in

**Comment by Faphouse** [comment]
OPPO F15
