### ISSUE TITLE
Verbiage of version

### ISSUE THREAD

**Issue by dnielsen2022** [skills/introduction-to-github#6]
**Describe the bug**
In Step 1, What is a branch section. There is a sentence that reads "You can make edits in your branch without impacting the main version." The word version could be confusing as the following sentence uses branch instead (which may be the better work in place of version?)

**To Reproduce**
1. Go to Step 1

**Expected behavior**
N/A

**Screenshots**
None

**Device information**
 Any

**Additional context**
None

**Comment by toxxicandco** [comment]
Tengo problemas para reproducir el sonido, Windows 11, lo hacía a veces en win 10,, tarjeta Realtek, bocina Bluetooth Bose, app Boom 3D, cualquier entrada, se cambia de configuración solo, cambia salida, no permite o simplemente no sale nada pero el medidor de volumen queda en n movimiento y activo, conexión con cable Jack 3.5mm igual problemas, aún peor.

**Comment by OccasionallyCoding** [comment]
@toxxicandco mi recomendación es preguntar la parte de discusiones o en otra página web. Espero que alguien te pueda ayudar aquí, pero no creo que es el mejor lugar para pedir ayuda como la que tú necesitas aquí.

**Comment by MisKeyceh1994** [comment]
> **Describe the bug** In Step 1, What is a branch section. There is a sentence that reads "You can make edits in your branch without impacting the main version." The word version could be confusing as the following sentence uses branch instead (which may be the better work in place of version?)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to Step 1
> 
> **Expected behavior** N/A
> 
> **Screenshots** None
> 
> **Device information** Any
> 
> **Additional context** None

About nt

**Comment by vladoss888** [comment]
D

**Comment by cmwilson21** [comment]
Closing this as it was addressed in the recent content refresh 💖
