### ISSUE TITLE
Videos are out of date

### ISSUE THREAD

**Issue by jimbobbennett** [skills/introduction-to-github#61]
**Describe the bug**

All the videos (except What is GitHub) are 7 years old. They show an outdated UI and include things like `master` as the canonical branch name. Not sure if you would class this as a bug or a feature request, but ideally these should be updated to show the correct UI and use the correct branch name of `main`.

**Comment by Faya753** [comment]
- [ ]

**Comment by heiskr** [comment]
Thanks for letting us know :) We have an internal issue with a request to another team to find or make updated videos.

**Comment by heiskr** [comment]
Thank you for opening this issue. We've removed these videos from our courses and YouTube.

**Comment by heiskr** [comment]
Sorry for the delayed response :) I'm trying to figure out what's going on with the videos, but it sounds like things are still in process for now.
