### ISSUE TITLE
[Bug] GitHub learning lab leads to a 404 page

### ISSUE THREAD

**Issue by dipikabh** [skills/introduction-to-github#682]
### Summary

As per the announcement, [learning lab was deprecated](https://github.blog/changelog/2022-09-01-deprecating-learning-lab/). 
However, the learning lab URL (https://lab.github.com/) is still available but leads to a 404 error page. 

You might want to redirect this to https://skills.github.com/.

### How to reproduce

1. Go to https://lab.github.com/.
2. See 404 error.

<img src="https://github.com/skills/introduction-to-github/assets/23019147/c3fa988f-7204-425f-8614-2c883dd85528" alt="screenshot of 404 error when you go to github learning lab" />

**Comment by Pasindusameera** [comment]
ok

**Comment by rachmari** [comment]
@dipikabh thank you for opening this up. We had the redirect from lab.github.com to skills.github.com active for 90 days, but had an expiration date defined to meet some internal requirements.

We don't plan to permanently redirect lab.github.com to skills.github.com, but we'd encourage folks to update any links to lab.github.com or contact folks that are the source of the link to get them updated.

If you come across any content that GitHub owns that links directly to lab.github.com, we'd be happy to update those old links to skills.github.com.

**Comment by dipikabh** [comment]
Thanks for the update @rachmari
