### ISSUE TITLE
Broken images links in README section

### ISSUE THREAD

**Issue by 7H3XXX** [skills/introduction-to-github#720]
### Summary

Screenshots of steps to follow throughout the courses don't show up.

### How to reproduce

1. Go to [the course](https://github.com/skills/introduction-to-github)
2. Click on 'Start course'
3. Create a new repository as prompted by the course
4. Wait 20 seconds
5. Scroll down to 'README section'
6. See error

### Screenshot

![Capture](https://github.com/skills/introduction-to-github/assets/49251439/e1bbcc98-0a82-4c55-b10c-4ad96349a281)

### Additional context

The problem may come from the link of the pictures, when clicking on any picture's link, it's says not found. Maybe using the the link of the file from the branch `main` can fix the error

**Comment by sinsukehlab** [comment]
I believe that this is resolved in #719. Feel free to provide the details if you still see broken images.

**Comment by heiskr** [comment]
Looks like this was fixed in #719.

**Comment by 7H3XXX** [comment]
Yes it's fixed, all the images are displayed normally
