### ISSUE TITLE
[Bug] Broken Images in Steps 2 and 3

### ISSUE THREAD

**Issue by JDPaiva1** [skills/introduction-to-github#731]
### Summary

In the activity section for steps 2 and 3, some images are not displaying correctly due to an quotation mark at the end of the image URL. This issue affects the following images:

https://github.com/skills/introduction-to-github/blob/86a4beabd429a43f345e87c8116b6f30f0ad7af0/.github/steps/2-commit-a-file.md?plain=1#L36

https://github.com/skills/introduction-to-github/blob/86a4beabd429a43f345e87c8116b6f30f0ad7af0/.github/steps/2-commit-a-file.md?plain=1#L40

https://github.com/skills/introduction-to-github/blob/86a4beabd429a43f345e87c8116b6f30f0ad7af0/.github/steps/3-open-a-pull-request.md?plain=1#L30

### How to reproduce

1. Go to step 2 or 3
3. Scroll down to the activity section

![image](https://github.com/skills/introduction-to-github/assets/29738138/76d12cbb-9e9b-4bd5-96b7-f1611894e45b)

![image](https://github.com/skills/introduction-to-github/assets/29738138/9b511500-27c1-4dd8-9537-6a36d035dc49)

**Comment by Tc69Cabusog** [comment]
How

**Comment by tipshep55** [comment]
Im fucked up! Lol

**Comment by ismail06kagit06** [comment]
Aboneliğimi iptal etmek.

28 Oca 2025 Sal 11:29 tarihinde tipshep55 ***@***.***> şunu
yazdı:
