### ISSUE TITLE
Enhance Course Content and Refactor Project Structure

### ISSUE THREAD

**Issue by AdityaSrivastava185** [skills/introduction-to-github#832]
### Summary

The intention behind these updates is to provide learners with a comprehensive understanding of open source contributions and the fundamentals of Git and GitHub. Before contributing to an open source project, it’s essential for learners to grasp these foundational concepts. The Welcome page has been reorganized to clearly explain key topics such as open source, its benefits, basic Git and GitHub terminology, and their usage.

### Changes

1.Added a "Next Lesson" file at the end of each chapter to enhance navigation.
2.Included detailed explanations of open source contribution fundamentals.
3.Added fundamental concepts of Git and GitHub.
4.Defined various types of software.
5.Updated course description and provided motivation.

**Comment by heiskr** [comment]
👋🏼 Thank you for your issue. This content would be out of scope for GitHub Skills. I'd recommend looking at our public docs at docs.github.com, the repository is https://github.com/github/docs.

**Comment by AdityaSrivastava185** [comment]
> 👋🏼 Thank you for your issue. This content would be out of scope for GitHub Skills. I'd recommend looking at our public docs at docs.github.com, the repository is https://github.com/github/docs.

Ohk , Thank you 😊
