### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by OccasionallyCoding** [skills/introduction-to-github#94]
**Describe the bug**
Grammatical Error

**To Reproduce**
1. Go to 'Step 2'
2. Scroll down to 'Numbered Point 5'
3. Look at the last 5 words of the first sentence.
4. See error between the words “what” and “changes”.

**Expected behavior**
This is an error that would be cleared up if deleted.

**Screenshots**
![Grammatical Error 2022-09-17 212610](https://user-images.githubusercontent.com/113797505/190885711-0490a15e-08cf-46a6-96db-8f5df187ad19.png)

**Device information**
 - Type: Amen Laptop
 - OS: Windows
 - Browser: Firefox
 - Version: 104.0.2 64-bit

**Additional context**
This will fix the grammatical error. That is the reason I gave it a 4/5 in the discussion. Otherwise, it would have been a 5/5.

**Comment by sinsukehlab** [comment]
Resolved in #35

**Comment by Nur-farah** [comment]
claim me

**Comment by Malik-RevelTek** [comment]
Welcome to my GitHub profile!

**Comment by genaldo1** [comment]
https://github.com/skills/introduction-to-github/issues/94#issue-1376941777[https://github.com/skills/introduction-to-github/issues/94#issue-1376941777](https://github.com/skills/introduction-to-github/issues/94#issue-1376941777)

**Comment by jhonnydss** [comment]
hi

**Comment by Alfiekmote20** [comment]
Unsubscribe

Pada tanggal Sab, 5 Nov 2022 11.37, Johnny David Santana Segura <
***@***.***> menulis:

**Comment by cmwilson21** [comment]
@OccasionallyCoding - Thanks for opening this issue! As stated above, looks like a separate PR updated this language. Closing this issue now 💛

**Comment by Alfiekmote20** [comment]
Unsubscribe

Pada tanggal Rab, 14 Des 2022 04.38, Courtney Wilson <
***@***.***> menulis:
