### ISSUE TITLE
code

### ISSUE THREAD

**Issue by LOHAYBOY999** [skills/introduction-to-github#941]
https://github.com/dkrivoruchko/ScreenStream/commit/c028fa9ad8732a6b06f59f86a9fac68b7b9f9dd6

**Comment by Mehahaha24578** [comment]
> [dkrivoruchko/ScreenStream@c028fa9](https://github.com/dkrivoruchko/ScreenStream/commit/c028fa9ad8732a6b06f59f86a9fac68b7b9f9dd6).close. delete

**Comment by Mehahaha24578** [comment]
> [dkrivoruchko/ScreenStream@c028fa9](https://github.com/dkrivoruchko/ScreenStream/commit/c028fa9ad8732a6b06f59f86a9fac68b7b9f9dd6).delete
