### ISSUE TITLE
MT PROJECT 

### ISSUE THREAD

**Issue by ratheesh228** [skills/introduction-to-github#993]
[maintainer edit for spammy content]

**Comment by Vzp1988** [comment]
> سلام. فکر می کنم شما سند را در جای اشتباهی آپلود کردید ...

ممنونم از لطف شما میتونید برام عکس ارسال کنید که کدوم رو باید ارسال کنم

**Comment by Vzp1988** [comment]
> > سلام. فکر می کنم شما سند را در جای اشتباهی آپلود کردید ...
> 
> ممنونم از لطف شما می توانید برام عکس ارسال کنید که کدوم رو باید ارسال کنید

چون سر در نمیارم خودم همکارم انجام داده خودشم سر در نیاورد چطور باید برگرده
